apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: 746387399152.dkr.ecr.us-west-1.amazonaws.com/rent-a-ride-backend:87df3142b-main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: mongo_uri
              value: mongodb://admin:password123@mongodb-svc:27017/rent-a-ride?authSource=admin

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"