apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: ecom
spec:
  selector:
    app: backend
  ports:
    - port: 3000  # <-- This is what Ingress uses
      targetPort: 3000